#server props
server:
  port: 8081
  servlet:
    context-path: /department-service/api/v1/


#application props    
spring:
#  application:
#    name: department-service

#database props
  datasource:
    url: jdbc:postgresql://localhost/college_students_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
   database-platform: org.hibernate.dialect.PostgreSQL9Dialect
   generate-ddl: true
   show-sql: true    
   properties:
    hibernate: 
#     ddl-auto: update 
#     jdbc: 
#     lob:
#        '[non_contextual_creation]': true
           

#log props
logging:
  level:
    root: info
    com.college.students: debug
  file: 
    path: logs/
    name: logs/my-app.log    


