#server props
server:
  port: 8081
  servlet:
    context-path: /department-service/api/v1/

#spring.servlet.multipart.max-file-size

#application props    
spring:
  servlet:
    multipart:
      max-file-size: 2MB
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    mapper:
      ALLOW_COERCION_OF_SCALARS: false
      
#  application:
#    name: student-service

#database props
  datasource:
    url: jdbc:postgresql://localhost/college_students_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
   database-platform: org.hibernate.dialect.PostgreSQL9Dialect
   generate-ddl: true
   show-sql: true    
   properties:
    hibernate: 
#     ddl-auto: update 
#     jdbc: 
#     lob:
#        '[non_contextual_creation]': true